INSERT OR IGNORE INTO entity_aliases (id,alias,entity_type,canonical_value) VALUES
-- Government and state terminology
('a-gov-nsg','NSG','government','Niger State Government'),
('a-gov-niger-govt','Niger State Govt','government','Niger State Government'),
('a-gov-state-government','state government','government','Niger State Government'),
('a-state-niger','Niger','state','Niger State'),
('a-state-power','Power State','state','Niger State'),

-- Senatorial zones
('a-zone-a','Zone A','senatorial_zone','Niger South'),
('a-zone-b','Zone B','senatorial_zone','Niger East'),
('a-zone-c','Zone C','senatorial_zone','Niger North'),
('a-zone-south','Niger South Senatorial District','senatorial_zone','Niger South'),
('a-zone-east','Niger East Senatorial District','senatorial_zone','Niger East'),
('a-zone-north','Niger North Senatorial District','senatorial_zone','Niger North'),

-- Local government areas and common forms
('a-lga-agaie','Agaie','lga','Agaie LGA'),
('a-lga-agwara','Agwara','lga','Agwara LGA'),
('a-lga-borgu','Borgu','lga','Borgu LGA'),
('a-lga-bosso','Bosso','lga','Bosso LGA'),
('a-lga-chanchaga','Chanchaga','lga','Chanchaga LGA'),
('a-lga-edati','Edati','lga','Edati LGA'),
('a-lga-gbako','Gbako','lga','Gbako LGA'),
('a-lga-gurara','Gurara','lga','Gurara LGA'),
('a-lga-katcha','Katcha','lga','Katcha LGA'),
('a-lga-kontagora','Kontagora','lga','Kontagora LGA'),
('a-lga-lapai','Lapai','lga','Lapai LGA'),
('a-lga-lavun','Lavun','lga','Lavun LGA'),
('a-lga-magama','Magama','lga','Magama LGA'),
('a-lga-mariga','Mariga','lga','Mariga LGA'),
('a-lga-mashegu','Mashegu','lga','Mashegu LGA'),
('a-lga-mokwa','Mokwa','lga','Mokwa LGA'),
('a-lga-munya','Munya','lga','Munya LGA'),
('a-lga-paikoro','Paikoro','lga','Paikoro LGA'),
('a-lga-rafi','Rafi','lga','Rafi LGA'),
('a-lga-rijau','Rijau','lga','Rijau LGA'),
('a-lga-shiroro','Shiroro','lga','Shiroro LGA'),
('a-lga-suleja','Suleja','lga','Suleja LGA'),
('a-lga-tafa','Tafa','lga','Tafa LGA'),
('a-lga-wushishi','Wushishi','lga','Wushishi LGA'),
('a-lga-minna','Minna','lga','Chanchaga LGA'),

-- Sectors and everyday terminology
('a-sec-medical','Medical','sector','Health'),
('a-sec-hospital','Hospitals','sector','Health'),
('a-sec-primary-health','Primary Healthcare','sector','Health'),
('a-sec-phc','PHC','sector','Health'),
('a-sec-schools','Schools','sector','Education'),
('a-sec-learning','Learning','sector','Education'),
('a-sec-basic-education','Basic Education','sector','Education'),
('a-sec-roads','Roads','sector','Works and Infrastructure'),
('a-sec-public-works','Public Works','sector','Works and Infrastructure'),
('a-sec-infrastructure','Infrastructure','sector','Works and Infrastructure'),
('a-sec-farming','Farming','sector','Agriculture'),
('a-sec-agric','Agric','sector','Agriculture'),
('a-sec-agro','Agro','sector','Agriculture'),
('a-sec-water-supply','Water Supply','sector','Water Resources'),
('a-sec-wash','WASH','sector','Water Resources'),
('a-sec-sanitation','Sanitation','sector','Water Resources'),
('a-sec-environmental','Environmental Protection','sector','Environment'),
('a-sec-climate','Climate Change','sector','Environment'),
('a-sec-digital','Digital Technology','sector','Information and Communication Technology'),
('a-sec-information-tech','Information Technology','sector','Information and Communication Technology'),
('a-sec-telecoms','Telecommunications','sector','Information and Communication Technology'),
('a-sec-transportation','Transportation','sector','Transport'),
('a-sec-homes','Homes','sector','Housing'),
('a-sec-social-welfare','Social Welfare','sector','Social Development'),
('a-sec-women-affairs','Women Affairs','sector','Social Development'),
('a-sec-youth-development','Youth Development','sector','Youth and Sports'),
('a-sec-sport','Sport','sector','Youth and Sports'),
('a-sec-trade','Trade','sector','Commerce and Industry'),
('a-sec-business','Business','sector','Commerce and Industry'),
('a-sec-msme','MSME','sector','Commerce and Industry'),
('a-sec-policing','Policing','sector','Security'),
('a-sec-emergency','Emergency Management','sector','Security'),
('a-sec-justice','Justice System','sector','Justice'),
('a-sec-legal','Legal Services','sector','Justice'),

-- Ministries, departments and agencies
('a-mda-moh','MOH','mda','Ministry of Health'),
('a-mda-health-ministry','Health Ministry','mda','Ministry of Health'),
('a-mda-moe','MOE','mda','Ministry of Education'),
('a-mda-education-ministry','Education Ministry','mda','Ministry of Education'),
('a-mda-mow','MOW','mda','Ministry of Works'),
('a-mda-mowa','Ministry of Works and Infrastructure','mda','Ministry of Works'),
('a-mda-agric-ministry','Agriculture Ministry','mda','Ministry of Agriculture'),
('a-mda-moa','MOA','mda','Ministry of Agriculture'),
('a-mda-finance-ministry','Finance Ministry','mda','Ministry of Finance'),
('a-mda-mof','MOF','mda','Ministry of Finance'),
('a-mda-budget-office','Budget Office','mda','Ministry of Budget and Planning'),
('a-mda-planning-commission','Planning Commission','mda','Ministry of Budget and Planning'),
('a-mda-water-ministry','Water Ministry','mda','Ministry of Water Resources'),
('a-mda-education-board','Education Board','mda','State Universal Basic Education Board'),
('a-mda-subeb','SUBEB','mda','State Universal Basic Education Board'),
('a-mda-nisubeb','NISUBEB','mda','Niger State Universal Basic Education Board'),
('a-mda-rural-roads','Rural Roads Agency','mda','Rural Access and Agricultural Marketing Project'),
('a-mda-raamp','RAAMP','mda','Rural Access and Agricultural Marketing Project'),
('a-mda-emergency','SEMA','mda','State Emergency Management Agency'),
('a-mda-primary-health','SPHCDA','mda','State Primary Health Care Development Agency'),
('a-mda-nsphcda','NSPHCDA','mda','Niger State Primary Health Care Development Agency'),
('a-mda-ict-agency','ICT Agency','mda','Information Technology Agency'),

-- Expenditure terminology
('a-exp-capex','CAPEX','expenditure_type','Capital'),
('a-exp-development','Development Expenditure','expenditure_type','Capital'),
('a-exp-capital-projects','Development Projects','expenditure_type','Capital'),
('a-exp-opex','OPEX','expenditure_type','Recurrent'),
('a-exp-running-cost','Running Costs','expenditure_type','Recurrent'),
('a-exp-operating','Operating Expenditure','expenditure_type','Recurrent'),
('a-exp-overhead','Overheads','expenditure_type','Recurrent'),
('a-exp-personnel','Personnel Costs','expenditure_type','Recurrent'),

-- Status and verification terminology
('a-status-in-progress','In Progress','status','ongoing'),
('a-status-underway','Underway','status','ongoing'),
('a-status-finished','Finished','status','completed'),
('a-status-done','Done','status','completed'),
('a-status-yet-start','Yet to Start','status','not started'),
('a-status-uncommenced','Uncommenced','status','not started'),
('a-status-stalled','Stalled','status','delayed'),
('a-status-held-up','Held Up','status','delayed'),
('a-status-authenticated','Authenticated','status','verified'),
('a-status-not-verified','Not Verified','status','unverified'),
('a-status-awaiting','Awaiting Review','status','pending');
