"use client";

import { useCallback, useEffect, useState } from "react";
import { Activity, BarChart3, Bot, Building2, Database, FileCheck2, FileUp, FolderKanban, HeartPulse, LogOut, MapPin, RefreshCw, Scale, Settings, ShieldAlert, ShieldCheck, ToggleRight, Upload, UserCog, UsersRound } from "lucide-react";
import { AiMonitoringPanel, AnalyticsPanel, SystemHealthPanel } from "@/components/admin-observability";
import { SecurityPanel } from "@/components/admin-security-panel";

export type Row = Record<string, string | number | null>;
type Metrics = { documents_ready?: number; documents_pending?: number; reports_pending?: number; ai_requests_today?: number; ingestion_failed?: number };
type Overview = { user?:{email:string;role:string}; budgets: Row[]; documents: Row[]; projects: Row[]; reports: Row[]; sectors: Row[]; mdas: Row[]; locations: Row[]; jobs: Row[]; logs: Row[]; metrics?: Metrics };
type SuperData = { administrators:Row[];configuration:Row[];sources:Row[];flags:Row[];approvals:Row[];auditLogs:Row[] };
const empty: Overview = { budgets: [], documents: [], projects: [], reports: [], sectors: [], mdas: [], locations: [], jobs: [], logs: [] };
const emptySuper:SuperData={administrators:[],configuration:[],sources:[],flags:[],approvals:[],auditLogs:[]};

export function AdminDashboard() {
  const [authenticated, setAuthenticated] = useState<boolean | null>(null);
  const [data, setData] = useState<Overview>(empty);
  const [tab, setTab] = useState("overview");
  const [notice, setNotice] = useState("");
  const [superData,setSuperData]=useState<SuperData>(emptySuper);

  const load = useCallback(async () => {
    const response = await fetch("/api/admin/overview", { cache: "no-store" });
    if (response.status === 401) return setAuthenticated(false);
    if (response.ok) { const overview=await response.json() as Overview; setData(overview); setAuthenticated(true); if(overview.user?.role==="super_administrator"){const privileged=await fetch("/api/superadmin",{cache:"no-store"});if(privileged.ok)setSuperData(await privileged.json())} }
  }, []);
  useEffect(() => { void load(); }, [load]);

  async function login(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const response = await fetch("/api/admin/session", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) });
    if (!response.ok) return setNotice("The credentials were not accepted.");
    setNotice(""); await load();
  }
  async function manage(resource: string, values: Record<string, string | number>) {
    const response = await fetch("/api/admin/manage", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ resource, values }) });
    const result = await response.json() as { error?: string };
    setNotice(response.ok ? "Record saved successfully." : result.error || "Unable to save record."); if (response.ok) await load();
  }

  if (authenticated === null) return <main className="admin-loading"><span className="brand-mark">G</span><p>Securing the workspace…</p></main>;
  if (!authenticated) return <main className="admin-login"><section className="admin-login-card"><div className="admin-login-brand"><span className="brand-mark">G</span><div><b>GANI Administration</b><small>Protected civic records workspace</small></div></div><ShieldCheck size={40}/><h1>Welcome back.</h1><p>Sign in to curate records, review evidence and monitor ingestion.</p><form onSubmit={login}><label>Email<input className="field" name="email" type="email" required autoComplete="username"/></label><label>Password<input className="field" name="password" type="password" required autoComplete="current-password"/></label>{notice && <p className="form-error">{notice}</p>}<button className="button" type="submit">Sign in securely</button></form><a href="/">← Return to public site</a></section></main>;

  const superAdmin=data.user?.role==="super_administrator";
  const nav = [{ id:"overview", label:"Overview", icon:Activity },{ id:"budgets",label:"Budgets",icon:Scale },{ id:"documents",label:"Documents",icon:FileCheck2 },{ id:"projects",label:"Projects",icon:FolderKanban },{ id:"taxonomy",label:"Directories",icon:Building2 },{ id:"reports",label:"Community reports",icon:UsersRound },{ id:"system",label:"System activity",icon:Database },{ id:"health",label:"System health",icon:HeartPulse },{ id:"ai",label:"AI monitoring",icon:Bot },{ id:"security",label:"Security",icon:ShieldAlert },{ id:"analytics",label:"Analytics",icon:BarChart3 },...(superAdmin?[{id:"super",label:"Super administration",icon:ShieldAlert}]:[])];
  return <div className="admin-shell"><aside className="admin-sidebar"><div className="admin-logo"><span className="brand-mark">G</span><div><b>GANI</b><small>Administration</small></div></div><nav>{nav.map(item=><button key={item.id} className={tab===item.id?"active":""} onClick={()=>setTab(item.id)}><item.icon size={17}/>{item.label}</button>)}</nav><div className="admin-user"><span>{superAdmin?"Super Administrator":"Administrator"}</span><small>{data.user?.email}</small><button onClick={async()=>{await fetch("/api/admin/session",{method:"DELETE"});setAuthenticated(false)}}><LogOut size={15}/> Sign out</button></div></aside><main className="admin-main"><header className="admin-top"><div><span className="kicker">Operations console</span><h1>{nav.find(item=>item.id===tab)?.label}</h1></div><div className="admin-status"><i/> Systems operational</div></header>{notice&&<div className="admin-notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
  {tab==="overview"&&<OverviewPanel data={data}/>} {tab==="budgets"&&<Budgets data={data} save={manage}/>} {tab==="documents"&&<Documents data={data} reload={load} notify={setNotice}/>} {tab==="projects"&&<Projects data={data} reload={load} notify={setNotice}/>} {tab==="taxonomy"&&<Taxonomy data={data} save={manage}/>} {tab==="reports"&&<Reports data={data} reload={load}/>} {tab==="system"&&<System data={data}/>} {tab==="health"&&<SystemHealthPanel/>} {tab==="ai"&&<AiMonitoringPanel/>} {tab==="security"&&<SecurityPanel/>} {tab==="analytics"&&<AnalyticsPanel/>} {tab==="super"&&superAdmin&&<SuperAdministration data={superData} reload={load} notify={setNotice}/>}</main></div>;
}

function OverviewPanel({data}:{data:Overview}) { const m=data.metrics||{}; const cards=[["Budget records",data.budgets.length,Scale],["Documents ready / pending",`${m.documents_ready??0} / ${m.documents_pending??0}`,FileCheck2],["Imported projects",data.projects.length,FolderKanban],["Reports awaiting review",m.reports_pending??data.reports.filter(r=>r.moderation_status==="pending").length,UsersRound],["AI requests today",m.ai_requests_today??0,Bot],["Failed ingestion jobs",m.ingestion_failed??0,HeartPulse]] as const; return <><div className="admin-metrics">{cards.map(([label,value,Icon])=><article key={label}><Icon/><span>{label}</span><strong>{value}</strong><small>In the operational database</small></article>)}</div><div className="admin-grid"><AdminTable title="Recent source records" rows={data.documents.slice(0,5)} columns={["title","year","processing_status"]}/><AdminTable title="Ingestion queue" rows={data.jobs.slice(0,5)} columns={["job_type","status","created_at"]}/></div></> }
function Budgets({data,save}:{data:Overview;save:(r:string,v:Record<string,string|number>)=>Promise<void>}) { return <div className="admin-grid wide-first"><FormCard title="Create budget record" onSubmit={f=>save("budgets",{budget_year:Number(f.get("budget_year")),title:String(f.get("title")),total_budget:Number(f.get("total_budget")),capital_expenditure:Number(f.get("capital_expenditure")||0),recurrent_expenditure:Number(f.get("recurrent_expenditure")||0),status:String(f.get("status"))})}><input className="field" name="budget_year" type="number" placeholder="Budget year" required/><input className="field" name="title" placeholder="Official title" required/><input className="field" name="total_budget" type="number" placeholder="Total approved amount (₦)" required/><div className="form-pair"><input className="field" name="capital_expenditure" type="number" placeholder="Capital amount"/><input className="field" name="recurrent_expenditure" type="number" placeholder="Recurrent amount"/></div><select className="field" name="status"><option>Approved</option><option>Draft</option><option>Archived</option></select></FormCard><AdminTable title="Budget records" rows={data.budgets} columns={["budget_year","title","total_budget","status"]}/></div> }
function Documents({data,reload,notify}:{data:Overview;reload:()=>Promise<void>;notify:(s:string)=>void}) { async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const res=await fetch("/api/admin/documents",{method:"POST",body:new FormData(e.currentTarget)});const out=await res.json() as {error?:string};notify(res.ok?"Document uploaded and queued for ingestion.":out.error||"Upload failed.");if(res.ok){e.currentTarget.reset();await reload()}} return <div className="admin-grid wide-first"><section className="admin-card"><h2><FileUp/> Upload source record</h2><p>Files remain private in R2 and are opened through controlled application routes.</p><form className="admin-form" onSubmit={upload}><input className="field" name="title" placeholder="Document title" required/><div className="form-pair"><input className="field" name="year" type="number" placeholder="Year" required/><select className="field" name="documentType"><option>Budget document</option><option>Procurement record</option><option>Policy</option><option>Audit report</option></select></div><input className="field" name="authority" placeholder="Issuing authority"/><label className="file-drop"><Upload/><b>Select a source file</b><small>PDF, spreadsheet or document · maximum 25 MB</small><input name="file" type="file" required/></label><button className="button">Upload and queue</button></form></section><section className="admin-card"><h2>Source records</h2>{data.documents.length?data.documents.map(d=><div className="admin-list-row" key={String(d.id)}><div><b>{d.title}</b><small>{d.year} · {d.processing_status}</small></div><QaIndexButton documentId={String(d.id)} notify={notify} reload={reload}/><button className="outline-button" onClick={async()=>{await fetch("/api/admin/documents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({documentId:d.id})});await reload()}}><RefreshCw size={13}/> Re-index</button></div>):<Empty text="No documents uploaded yet."/>}</section></div> }
function Projects({data,reload,notify}:{data:Overview;reload:()=>Promise<void>;notify:(s:string)=>void}) { async function importFile(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{const rows=JSON.parse(await file.text());const res=await fetch("/api/admin/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projects:rows})});const out=await res.json() as {error?:string;imported?:number};notify(res.ok?`${out.imported} projects imported.`:out.error||"Import failed.");if(res.ok)await reload()}catch{notify("Upload a valid JSON array of project records.")}} return <><section className="admin-card admin-import"><div><h2>Import verified projects</h2><p>Import only records traceable to a public source. Existing project codes are updated.</p></div><label className="button"><Upload size={15}/> Choose JSON file<input type="file" accept="application/json" onChange={importFile}/></label></section><AdminTable title="Project register" rows={data.projects} columns={["project_code","title","budget_year","approved_amount","verification_status"]}/></> }
function Taxonomy({data,save}:{data:Overview;save:(r:string,v:Record<string,string|number>)=>Promise<void>}) { return <div className="taxonomy-grid"><QuickDirectory title="Sectors" icon={<Scale/>} rows={data.sectors} fields={["name","slug","description"]} save={v=>save("sectors",v)}/><QuickDirectory title="MDAs" icon={<Building2/>} rows={data.mdas} fields={["name","type"]} save={v=>save("mdas",v)}/><QuickDirectory title="Locations" icon={<MapPin/>} rows={data.locations} fields={["name","type","senatorial_zone"]} save={v=>save("locations",{...v,state:"Niger"})}/></div> }
function Reports({data,reload}:{data:Overview;reload:()=>Promise<void>}) { async function review(id:string,status:string){await fetch("/api/admin/manage",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({reportId:id,moderationStatus:status,verificationStatus:status==="approved"?"reviewed":"unverified"})});await reload()} return <section className="admin-card"><h2>Community review queue</h2>{data.reports.length?data.reports.map(r=><div className="report-review" key={String(r.id)}><div><span className="tag">{r.report_status}</span><h3>{r.observation||"No written observation"}</h3><small>Submitted {r.submitted_at} · {r.verification_status}</small>{r.evidence_r2_key&&<small><a href={`/api/admin/reports/${r.id}/photo`} target="_blank" rel="noreferrer">View photo evidence</a></small>}</div><div><button className="outline-button" onClick={()=>review(String(r.id),"rejected")}>Reject</button><button className="button" onClick={()=>review(String(r.id),"approved")}>Approve</button></div></div>):<Empty text="No community reports are awaiting review."/>}</section> }
function System({data}:{data:Overview}) { return <div className="admin-grid"><AdminTable title="Ingestion status" rows={data.jobs} columns={["job_type","status","detail","updated_at"]}/><AdminTable title="AI and system log" rows={data.logs} columns={["event_type","summary","status","created_at"]}/></div> }
function SuperAdministration({data,reload,notify}:{data:SuperData;reload:()=>Promise<void>;notify:(s:string)=>void}) {
  const [section,setSection]=useState("administrators");
  async function send(method:"POST"|"PATCH",payload:Record<string,unknown>){const response=await fetch("/api/superadmin",{method,headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as {error?:string};notify(response.ok?"Super administrator change saved.":result.error||"Change failed.");if(response.ok)await reload()}
  const items=[["administrators","Administrators",UserCog],["configuration","Configuration",Settings],["sources","Data sources",Database],["ai","AI settings",Bot],["flags","Feature flags",ToggleRight],["approvals","Approvals",ShieldAlert],["audit","Audit log",FileCheck2]] as const;
  return <><div className="super-tabs">{items.map(([id,label,Icon])=><button className={section===id?"active":""} onClick={()=>setSection(id)} key={id}><Icon size={14}/>{label}</button>)}</div>
  {section==="administrators"&&<div className="admin-grid wide-first"><FormCard title="Create administrator" onSubmit={f=>send("POST",{action:"create_administrator",values:Object.fromEntries(f)})}><input className="field" name="display_name" placeholder="Full name" required/><input className="field" name="email" type="email" placeholder="Email" required/><input className="field" name="password" type="password" minLength={12} placeholder="Temporary password · 12+ characters" required/><select className="field" name="role"><option value="administrator">Administrator</option><option value="super_administrator">Super administrator</option></select></FormCard><section className="admin-card"><h2>Administrator accounts</h2>{data.administrators.length?data.administrators.map(a=><div className="admin-list-row" key={String(a.id)}><div><b>{a.display_name}</b><small>{a.email} · {String(a.role).replaceAll("_"," ")} · {a.status}</small></div><button className="outline-button" onClick={()=>send("PATCH",{action:"administrator_status",id:a.id,status:a.status==="active"?"suspended":"active"})}>{a.status==="active"?"Suspend":"Activate"}</button></div>):<Empty text="No delegated administrator accounts."/>}</section></div>}
  {(section==="configuration"||section==="ai")&&<div className="admin-grid wide-first"><FormCard title={section==="ai"?"Update AI setting":"Update configuration"} onSubmit={f=>send("POST",{action:"save_configuration",values:{...Object.fromEntries(f),category:section==="ai"?"ai":"system"}})}><input className="field" name="config_key" placeholder={section==="ai"?"ai.setting_name":"system.setting_name"} required/><input className="field" name="config_value" placeholder="Value" required/><input className="field" name="description" placeholder="Description"/></FormCard><AdminTable title={section==="ai"?"AI control settings":"System configuration"} rows={data.configuration.filter(r=>r.category===(section==="ai"?"ai":"system"))} columns={["config_key","config_value","description","updated_at"]}/></div>}
  {section==="sources"&&<div className="admin-grid wide-first"><FormCard title="Register trusted data source" onSubmit={f=>send("POST",{action:"create_source",values:Object.fromEntries(f)})}><input className="field" name="name" placeholder="Source name" required/><input className="field" name="source_url" type="url" placeholder="https://…" required/><select className="field" name="source_type"><option value="official_portal">Official portal</option><option value="official_document">Official document repository</option><option value="enactment_report">Enactment report</option></select><select className="field" name="trust_level"><option value="trusted">Trusted</option><option value="review_required">Review required</option></select></FormCard><section className="admin-card"><h2>Registered data sources</h2>{data.sources.map(s=><div className="admin-list-row" key={String(s.id)}><div><b>{s.name}</b><small>{s.source_type} · {s.source_url}</small></div><button className="outline-button" onClick={()=>send("PATCH",{action:"source_status",id:s.id,enabled:!s.enabled})}>{s.enabled?"Disable":"Enable"}</button></div>)}</section></div>}
  {section==="flags"&&<section className="admin-card"><h2>Feature flags</h2>{data.flags.map(flag=><div className="flag-row" key={String(flag.flag_key)}><div><b>{flag.label}</b><small>{flag.description}</small></div><button className={`flag-toggle ${flag.enabled?"on":""}`} aria-pressed={Boolean(flag.enabled)} onClick={()=>send("PATCH",{action:"feature_flag",key:flag.flag_key,enabled:!flag.enabled})}><i/></button></div>)}</section>}
  {section==="approvals"&&<div className="admin-grid wide-first"><FormCard title="Request destructive operation" onSubmit={f=>send("POST",{action:"request_operation",values:Object.fromEntries(f)})}><select className="field" name="operation_type"><option value="delete_record">Delete record</option><option value="purge_document">Purge document</option><option value="reset_index">Reset search index</option></select><input className="field" name="target_type" placeholder="Target type" required/><input className="field" name="target_id" placeholder="Exact target ID" required/><textarea className="field" name="reason" minLength={10} placeholder="Reason and expected impact" required/></FormCard><section className="admin-card"><h2>Approval queue</h2>{data.approvals.length?data.approvals.map(a=><div className="approval-row" key={String(a.id)}><div><span className="tag">{a.status}</span><b>{a.operation_type} · {a.target_id}</b><small>{a.reason}</small></div>{a.status==="pending"&&<div><button className="outline-button" onClick={()=>send("PATCH",{action:"review_operation",id:a.id,status:"rejected"})}>Reject</button><button className="button" onClick={()=>send("PATCH",{action:"review_operation",id:a.id,status:"approved"})}>Approve</button></div>}</div>):<Empty text="No destructive operations awaiting approval."/>}</section></div>}
  {section==="audit"&&<AdminTable title="System audit log" rows={data.auditLogs} columns={["created_at","actor","event_type","summary","status"]}/>}</>;
}
function FormCard({title,onSubmit,children}:{title:string;onSubmit:(form:FormData)=>void;children:React.ReactNode}) { return <section className="admin-card"><h2>{title}</h2><form className="admin-form" onSubmit={e=>{e.preventDefault();void onSubmit(new FormData(e.currentTarget));e.currentTarget.reset()}}>{children}<button className="button">Save record</button></form></section> }
function QuickDirectory({title,icon,rows,fields,save}:{title:string;icon:React.ReactNode;rows:Row[];fields:string[];save:(v:Record<string,string>)=>void}) { return <section className="admin-card"><h2>{icon}{title}</h2><form className="quick-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save(Object.fromEntries(fields.map(k=>[k,String(f.get(k)||"")])));e.currentTarget.reset()}}>{fields.map(f=><input key={f} className="field" name={f} placeholder={f.replaceAll("_"," ")} required={f==="name"}/>) }<button className="button">Add</button></form><div className="directory-list">{rows.map(r=><div key={String(r.id)}><b>{r.name}</b><small>{r.type||r.slug||r.senatorial_zone||"—"}</small></div>)}</div></section> }
export function AdminTable({title,rows,columns}:{title:string;rows:Row[];columns:string[]}) { return <section className="admin-card table-card"><h2>{title}</h2>{rows.length?<div className="admin-table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id||i)}>{columns.map(c=><td key={c}>{c.includes("amount")||c==="total_budget"?Number(row[c]||0).toLocaleString("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}):String(row[c]??"—")}</td>)}</tr>)}</tbody></table></div>:<Empty text={`No ${title.toLowerCase()} yet.`}/>}</section> }
function QaIndexButton({documentId,notify,reload}:{documentId:string;notify:(s:string)=>void;reload:()=>Promise<void>}) {
  const [busy,setBusy]=useState(false);
  async function index(){
    setBusy(true);
    let offset=0;
    let total=0;
    try{
      while(true){
        const response=await fetch("/api/admin/index-document",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({documentId,offset})});
        const result=await response.json() as {error?:string;indexed?:number;nextOffset?:number|null};
        if(!response.ok)throw new Error(result.error||"Document Q&A indexing failed.");
        total+=result.indexed||0;
        notify(`Indexed ${total} passages for document Q&A…`);
        if(result.nextOffset==null)break;
        offset=result.nextOffset;
      }
      notify(`Document Q&A index complete: ${total} passages.`);
      await reload();
    }catch(error){notify(error instanceof Error?error.message:"Indexing failed.")}
    finally{setBusy(false)}
  }
  return <button className="outline-button" disabled={busy} onClick={()=>void index()}><Bot size={13}/>{busy?"Indexing…":"Index Q&A"}</button>;
}

export function Empty({text}:{text:string}) { return <div className="admin-empty"><Database/><p>{text}</p></div> }
