import Link from "next/link";import {ArrowRight,Bot,Database,FileCheck2,Landmark,ShieldCheck,Sparkles,TrendingDown} from "lucide-react";import {budgets,formatMoney,latestBudget} from "@/lib/data";import {HeroAsk} from "@/components/hero-ask";import {ViewRecordButton} from "@/components/view-record-button";import {getBudgetSummary,getTopSectors} from "@/lib/repo-overview";
const prompts=["How much was allocated to healthcare?","What projects are planned for Bida?","Which ministry has the highest allocation?","Explain the 2026 budget in simple English."];
const SECTOR_ICON_CLASSES=["s1","s2","s3","s4","s1"];
export async function Home(){const max=Math.max(...budgets.map(b=>b.approved));const [summary,sectors]=await Promise.all([getBudgetSummary(latestBudget.year),getTopSectors(latestBudget.year)]);return <>
<section className="hero"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-inner"><div className="hero-copy-block"><div className="eyebrow"><Sparkles size={14}/> Source-backed public accountability</div><h1>Understand where <em>public money goes.</em></h1><p className="hero-copy">Explore nine document-backed Niger State approved annual budgets (2018–2026), ask questions in everyday language and open the evidence behind each figure.</p><HeroAsk prompts={prompts}/></div>
<div className="hero-visual"><div className="visual-topline"><span><span className="live-dot"/> Approved appropriation</span><span className="visual-seal"><Landmark size={15}/></span></div><p className="mini-question">“What is Niger State’s 2026 approved budget?”</p><div className="visual-answer"><span className="mini-gani">G</span><div><small>2026 approved appropriation</small><strong>{latestBudget.display}</strong><p>Budget of Consolidation</p></div></div><div className="mini-chart"><div className="chart-head"><span>Ten-year approved-budget series</span><TrendingDown size={14}/></div>{budgets.slice(-3).map(b=><div className="chart-row" key={b.year}><span>{b.year}</span><i style={{width:`${Math.max(8,b.approved/max*100)}%`}}/><b>{b.display.replace("₦","")}</b></div>)}</div><div className="mini-evidence"><ShieldCheck size={17}/><span><b>Source linked</b><small>Appropriation passage · 23 Dec 2025</small></span><ViewRecordButton/></div><div className="floating-badge"><FileCheck2/><span><b>Sources attached</b><small>Open every record</small></span></div></div></div></section>
<section className="trust-strip"><div><FileCheck2/><span><b>Approved records</b><small>Not proposals</small></span></div><ArrowRight/><div><Database/><span><b>Comparable series</b><small>Original budgets</small></span></div><ArrowRight/><div><Bot/><span><b>AI explanation</b><small>Plain language</small></span></div><ArrowRight/><div><ShieldCheck/><span><b>You verify</b><small>Open every source</small></span></div></section>
<section className="statement"><span className="quote-mark">“</span><p>GANI does not ask you to trust a number blindly. <strong>Every figure in this series has a traceable source.</strong></p></section>
<section className="snapshot section"><div className="section-head"><div><span className="kicker">Budget at a glance</span><h2>{summary.year} budget snapshot</h2><p>Live figures queried from the operational database — nothing here is hard-coded.</p></div><Link href="/budget" className="text-link">Explore the series <ArrowRight size={16}/></Link></div><div className="metric-grid"><article className="metric featured"><small>Analysed budget</small><strong>{formatMoney(summary.analysedBudget)}</strong><span>{summary.year} approved appropriation</span></article><article className="metric"><small>Projects analysed</small><strong>{summary.projectCount}</strong><span>Verified project records</span></article><article className="metric"><small>MDAs covered</small><strong>{summary.mdaCount}</strong><span>Ministries, departments &amp; agencies</span></article><article className="metric"><small>Sectors covered</small><strong>{summary.sectorCount}</strong><span>Classified sectors</span></article></div></section>
{sectors.length>0&&<section className="section"><div className="section-head"><div><span className="kicker">Sector preview</span><h2>Explore spending by sector</h2><p>Selecting a sector opens its filtered project records.</p></div></div><div className="sector-grid">{sectors.map((s,i)=><Link href={`/projects?sector=${s.slug}`} className="sector-card" key={s.slug}><div><span className={`sector-icon ${SECTOR_ICON_CLASSES[i%SECTOR_ICON_CLASSES.length]}`}>{s.name.charAt(0)}</span><ArrowRight size={14}/></div><h3>{s.name}</h3><strong>{formatMoney(s.totalAllocation)}</strong><p>{s.projectCount} project{s.projectCount===1?"":"s"}</p></Link>)}</div></section>}
<section className="section"><div className="section-head"><div><span className="kicker">Source ledger</span><h2>See every annual record</h2></div><Link href="/documents" className="text-link">Open documents <ArrowRight size={16}/></Link></div><div className="budget-ledger">{budgets.slice().reverse().map(b=><a href={b.sourceUrl} target="_blank" rel="noreferrer" className="ledger-row" key={b.year}><span>{b.year}</span><strong>{b.display}</strong><small>{b.precision==="exact"?"Exact figure":"Published rounded figure"}</small><ArrowRight size={16}/></a>)}</div></section>
<section className="cta"><div className="bot-orb"><Bot/></div><div><span className="kicker light">Ask. Understand. Verify.</span><h2>Public records, without the guesswork.</h2><p>Ask GANI to compare years, calculate changes or explain what an approved budget means.</p></div><Link href="/ask" className="button light-button">Start asking <ArrowRight size={17}/></Link></section></>}
